In [26]:
import pandas as pd 
from sklearn.model_selection import train_test_split

In [27]:
data = {
    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Passed": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
print(df)

   Hours_Studied  Passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       0
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [28]:
df = pd.DataFrame(data)

In [29]:
X = df[['Hours_Studied']] 
y = df['Passed']

In [30]:
X.shape

(10, 1)

In [31]:
y.shape

(10,)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
X_train

   Hours_Studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [34]:
X_test

   Hours_Studied
8              9
1              2

In [35]:
y_train

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: Passed, dtype: int64

In [36]:
# import logistic regression

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
# create and train model

In [39]:
model=LogisticRegression()

In [42]:
model.fit(X_train,y_train)

LogisticRegression()

In [43]:

#prediction

In [44]:
y_pred=model.predict(X_test)

In [46]:
y_pred

array([1, 0])

In [47]:
X_test

   Hours_Studied
8              9
1              2

In [48]:
import pandas as pd

In [52]:
new=pd.DataFrame({'Hours_Studied':[7.5]})
predicted_value=model.predict(new)
predicted_value

array([1])

In [57]:
from sklearn.metrics import accuracy_score

In [59]:
accuracy= accuracy_score(y_test,y_pred)

In [60]:
accuracy

1.0

In [61]:
y_prob=model

In [62]:
y_prob=model.predict_proba(X_test)

In [64]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])